---
version: "3"

services:

  drupal-vm:

    # If using a custom baked image, change the name below to your image's name.
    image: geerlingguy/drupal-vm
    # Comment out 'image' and uncomment the line below if customizing Drupal VM
    # with a project-specific Dockerfile in the same directory as this file.
    # build: .

    # Set this to your project's machine name (e.g. example-com)
    container_name: drupal-vm

    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 8025:8025

    # Not strictly required, but custom DNS settings can help with stability.
    dns:
      - '8.8.8.8'
      - '8.8.4.4'

    volumes:
      - ./:/var/www/drupalvm/:rw,delegated
      - /var/lib/mysql
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

    privileged: true
    command: /lib/systemd/systemd
